name: Build FiveM Client

on:
  workflow_dispatch: # Pozwala ręcznie odpalić kompilację w zakładce "Actions"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md' # Ignoruje zmiany w plikach tekstowych

jobs:
  build-client:
    name: Kompilacja klienta (Windows)
    runs-on: windows-2022

    steps:
      - name: Konfiguracja Gita dla symlinków
        # FiveM wymaga symlinków, co jest domyślnie wyłączone w Windowsie
        run: git config --global core.symlinks true

      - name: Pobieranie kodu repozytorium (Checkout)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Konfiguracja Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalacja setuptools (Wymagane przez skrypty)
        run: pip install setuptools

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Budowanie projektu (fxd)
        # Używamy jednego kroku CMD, aby środowisko poprawnie dziedziczyło zmienne systemowe
        shell: cmd
        run: |
          :: Pobranie odpowiedniej wersji Chromium dla FiveM
          call fxd.cmd get-chrome
          
          :: Zbudowanie bindingów (Natives)
          call prebuild.cmd
          
          :: Wygenerowanie plików projektu FastBuild/MSbuild dla klienta
          call fxd.cmd gen -game five
          
          :: Właściwa kompilacja
          call fxd.cmd build -game five

      - name: Zapisanie gotowego klienta (Artefakty)
        uses: actions/upload-artifact@v4
        with:
          name: FiveM-Client-Debug
          path: code/bin/five/debug/
